---

#####
##   The main playbook for installing ALPv2.
##   Intended for use with a modern Ubuntu version
##   First, ensure that your server is listed in the inventory file
##   You need to be able to access the server through SSH keys
##   The user you log in as needs to have sudo rights

- name: Install ALPv2

  #####
  ##  This playbook is intended to be run on the server that it is configuring
  hosts: localhost
  connection: local

  vars:
    nud_user: nurpc
    postgresql_version: 9.5

  vars_prompt:

    #####
    ## ALP
    - name: pool_name
      prompt: what is the name of your pool?

    #####
    ## Nginx
    - name: pool_server_domain_name
      prompt: what is the domain name where your pool can be accessed?

    #####
    ## LetsEncrypt
    - name: letsencrypt_admin_email
      prompt: what email address would you like to use for notifiction of your ssl certificate expiry


    #####
    ## Nud
    #- name: nud_password
    #  prompt: create a password
#
#    #####
#    ## PostgreSQL
#
#    root_postgresql_password: Sincere^Split#Rich%Cap&Offer&Far#Out%10
#    alp_user_postgres_password: Wake$Effective&Extreme#Relation!Horse&Material^Wheel^10



  #####
  ##  These roles will be run in this order
  roles:
    - update_and_install_dependencies
    #- create_users
    #- install_postgresql
    #- install_nginx
    #- letsencrypt
    #- install_nud
    #- install_alp2
    #- install_supervisor
    #- configure_firewall
