---

#####
##   The main playbook for installing ALPv2.
##   Intended for use with a modern Ubuntu version
##   First, ensure that your server is listed in the inventory file
##   You need to be able to access the server through SSH keys
##   The user you log in as needs to have sudo rights

- name: Install ALPv2

  #####
  ##  This playbook is intended to be run on the server that it is configuring
  hosts: localhost
  connection: local

  vars:
    #####
    ## nud
    nud_user: alp_nurpc_user
    nud_password: "{{ lookup('password', '/tmp/nudpasswordfile') }}"
    #####
    ## PostgreSQL
    postgresql_version: 9.5
    root_postgresql_password: "{{ lookup('password', '/tmp/rootpostgrespasswordfile') }}"
    alp_user_postgres_password: "{{ lookup('password', '/tmp/alppostgrespasswordfile') }}"

  vars_prompt:
    #####
    ## ALP
    - name: pool_name
      prompt: What is the name of your pool?
      private: no
    #####
    ## Nginx
    - name: pool_server_domain_name
      prompt: What is the domain name where your pool can be accessed?
      private: no
    #####
    ## LetsEncrypt
    - name: letsencrypt_admin_email
      prompt: Which email address would you like to be notified when your ssl certificate nears expiry? (Leave blank to skip certificate generation and serve the poool on http only)
      private: no

  #####
  ##  These roles will be run in this order
  roles:
    - update_and_install_dependencies
    - create_users
    - install_postgresql
    - install_nginx
    - install_nud
    - install_alp2
    - configure_supervisor
    - configure_firewall
    - role: letsencrypt
      when: letsencrypt_admin_email != ""
