---

#####
## Update apt, upgrade and install dependencies

- name: update and upgrade
  become: yes
  apt:
    update_cache: yes
    upgrade: dist

- name: install dependencies
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - fail2ban
    - git
    - libffi-dev
    - python
    - python-dev
    - python-pip
    - python-virtualenv
    - nginx
    - nginx-extras
    - supervisor
    - unzip
    - vim
