---

#####
## Update apt, upgrade and install dependencies

- name: update and upgrade
  become: yes
  apt:
    update_cache: yes
    upgrade: dist

- name: install dependencies
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - python
    - python-dev
    - python-passlib
    - libffi-dev
    - python-pip
    - python-virtualenv
    - git
    - nginx
    - nginx-extras
    - unzip

- name: test password generation
  command: python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.encrypt(getpass.getpass())"
  register: password

- debug:
    msg: "{{ password }}"
