---

#####
##  Create the alp user
#####

- name: create alp group
  become: yes
  group:
    name: alp

- name: create alp user
  become: yes
  user:
    name: alp
    shell: /bin/bash
    state: present
    group: alp

- name: create the logs directory for the alp user
  file:
    name: /home/alp/logs
    state: directory
    owner: alp
    group: alp
    mode: 0755

- name: create the logs/nginx directory for the nginx access and error logs
  file:
    name: /home/alp/logs/nginx
    state: directory
    owner: alp
    group: alp
    mode: 0755

#####
##  Create the nud user
#####

- name: create nud group
  become: yes
  group:
    name: nud

- name: create nud user
  become: yes
  user:
    name: nud
    shell: /bin/bash
    state: present
    group: nud
