---

#####
##  Configure the firewall

- name: reset firewall to start off blank
  become: yes
  ufw:
    state: reset
    policy: deny

- name: allow ssh
  become: yes
  ufw:
    rule: allow
    port: ssh
    proto: tcp
    state: enabled

- name: allow http
  become: yes
  ufw:
    rule: allow
    port: http
    proto: tcp
    state: enabled

- name: allow https
  become: yes
  ufw:
    rule: allow

    port: https
    proto: tcp
    state: enabled
  when: letsencrypt_admin_email != ""

