---

#####
##  Get a free SSL certificate from Lets encrypt

- name: update certificates
  become: yes
  command:  update-ca-certificates

- name: create nginx ssl directory
  become: yes
  file:
    path: /etc/nginx/ssl
    state: directory
    owner: root
    group: root
    mode: 0644

- name: generate Diffie-Hellman prime
  become: yes
  command: openssl dhparam -rand - 2048 -out dhparam.pem
  args:
    chdir: /etc/nginx/ssl/
    creates: /etc/nginx/ssl/dhparam.pem

- name: clone letsencrypt repo
  git:
    repo: https://github.com/letsencrypt/letsencrypt
    dest: ~/letsencrypt

- name: ensure webroot exists
  become: yes
  file:
    name: /var/www/letsencrypt
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

- name: run letsencrypt client
  shell: ./letsencrypt-auto certonly --webroot -w /var/www --agree-tos --keep-until-expiring --email {{ letsencrypt_admin_email }} --rsa-key-size 4096 --text -d {{ pool_server_domain_name }}
  args:
    chdir: ~/letsencrypt
  register: output

- name: template alp nginx ssl conf
  become: yes
  template:
    src: alp-ssl.conf.j2
    dest: /etc/nginx/conf.d/alp.conf
    mode: 0644
    owner: root
    group: root

- name: restart nginx
  become: yes
  supervisorctl:
    name: nginx
    state: restarted